### PR TITLE
Implement pull request searching

### LINKED ISSUE #28: add support for PR filters
Thinks this could be implemented using GH's [Search Issues](https://developer.github.com/v3/search/#search-issues) API.
I'm particularly interested into tag and user filters, like https://github.com/dlang/phobos/pulls?q=is:open+is:pr+review-requested:MartinNowak+label:stalled.
Ideally this would just be a `?q=` parameter on the pullfeed endpoint as well.

### PR DESCRIPTION
**Pull request by rhendric**
By adding a `q` query parameter to the feed URL, users can subscribe to
a subset of open pull requests instead of all of them. The `q` parameter
uses GitHub's search API and thus supports the search syntax used by
GitHub, documented here:
https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax

Closes #28.

### CODE REVIEW

**Comment by edwardloveall** [comment]
Thanks so much for this PR! I appreciate you getting this working on my neglected side project. I did a quick pass over the change and it looks good but I'll need to add a search fixture to make your tests pass (or you're welcome to do that).

**Comment by rhendric** [comment]
Oh, oops! Missed that in the commit.

**Comment by edwardloveall** [comment]
Notes for future me:

* GitHub's ReST search API has a authenticated rate limit of 30 requests per minute
* After investigating pullfeed's logs, the traffic is well under that number

**Comment by edwardloveall** [comment]
Thanks @rhendric! I switch the paragraph order on the homepage, but otherwise this looks great!

**Comment by rhendric** [comment]
Thank *you* for providing this service!

**Pull request merged**
